### ISSUE TITLE
Please add other maintainers

### ISSUE THREAD

**Issue by boshek** [cran-task-views/Hydrology#104]
:wave: @zeileis 

Could you please give @ilapros and @samzipper write access to this repo? They are also maintainers. 

Sam and Ilaria this is a good read to familiarize yourself with the new format: https://ctv.r-forge.r-project.org/articles/ctv-howto.html

**Comment by zeileis** [comment]
They had already "Write" access, I just changed their GitHub roles to "Maintainer". Your role @boshek is now "Admin". Thus, if necessary, you can also make such changes yourself in the future.
