### ISSUE TITLE
Several R packages to add to Hydrological Data and Modeling CRAN Task View

### ISSUE THREAD

**Issue by iembry** [cran-task-views/Hydrology#107]
Greetings, I would like for you to add the following R packages (all of them are on CRAN except for the last one) to the Hydrological Data and Modeling CRAN Task View:

iemisc, iemiscdata, ie2misc, ie2miscdata, airGRiwrm, soilhypfit, IDF, htsr, hydraulics, riverdist, RiverLoad, SWTools, openSTARS, waterquality, RWDataPlyr, reasonabletools, DWBmodelUN, dbhydroR, dynatop, dynatopGIS, baytrends, Raquifer, RGENERATEPREC, gsw, OCNet, SBN, gwavr, epanet2toolkit, epanetReader, IETD, VIC5, DeductiveR, noaastormevents, swmmr, transfR, and https://github.com/cvitolo/curvenumber

I want to thank you in advance for your time and consideration.

Irucka Embry

**Comment by boshek** [comment]
Hi there. That's a lot of packages! Would you consider opening a pull request with at least some these formatted like all the packages are in [this](https://raw.githubusercontent.com/cran-task-views/Hydrology/main/Hydrology.md) file?

**Comment by iembry** [comment]
@boshek    Hi Sam, yes, I will do a pull request for all of the packages with the requested formatting. I should hopefully have that completed within the next week or so.

Thank you for the suggestion.

**Comment by boshek** [comment]
Happy to answer any questions @iembry. Really appreciate the contribution.
