### ISSUE TITLE
delayedflow: Package for Baseflow Separation with multiple contributions

### ISSUE THREAD

**Issue by modche** [cran-task-views/Hydrology#112]
Dear all,

perhaps it is valuable to add my delayedflow package to the CRAN task list.

```
#install.packages("devtools")
devtools::install_github("modche/delayedflow")
```

Package Manual: https://modche.github.io/delayedflow/

Paper: https://hess.copernicus.org/articles/24/849/2020/

**Comment by boshek** [comment]
👋 @modche - thanks for this. Any plans to submit this to CRAN? We do accept some packages that are github only but the desire is for these to be _CRAN_ task views.

**Comment by modche** [comment]
Thanks. Yes, CRAN is planned for the future (end of the year).

**Comment by boshek** [comment]
Great! Can you please edit the [markdown](https://github.com/cran-task-views/Hydrology/blob/main/Hydrology.md) file? There are a couple GitHub examples in there.

**Comment by boshek** [comment]
👋 @modche - any plans to submit to CRAN soon? If not I will close this issue. Thanks!
