### ISSUE TITLE
agromet

### ISSUE THREAD

**Issue by jpiaskowski** [cran-task-views/Hydrology#113]
Hello,

I'd like to suggest the package 'agromet', which is not CRAN, but it is on GitHub: 

https://github.com/AgRoMeteorologiaINTA/agromet. 

This package includes a series of functions to calculate climatic and hydrological indices and statistics from tidy data.

This may fit the category "Hydrological data sources".

I am building an agricultural CTV. This package is relevant to our audience, but it's a better fit in your CTV. 

On a complete unrelated note, you may want to consider creating templates for users to submit issues for new packages. Here is what we use (adapted from the reproducible research CTV): https://github.com/IdahoAgStats/ctv-agriculture/tree/main/.github/ISSUE_TEMPLATE

Thank you,

Julia

**Comment by boshek** [comment]
This is a great suggestion for the issue template (and probably a pull request one too).

Curious - how are you approaching GitHub packages? I hate to paint with broad strokes but largely CRAN packages assure some sort of quality. But at the same time, I'd hate to miss out on some great content.

**Comment by jpiaskowski** [comment]
I'm not sure what you mean by "quality." This was a community-suggested package, and I trust the community. I don't think CRAN assures a level of statistical quality, adequacy of documentation or sufficient error checking in the code. Their [checklist](https://cran.r-project.org/web/packages/policies.html) is designed to ensure a package doesn't break someone's R installation, but doesn't go much beyond that. Using any R package is a risk we all take, so I look for packages that are (1) open source so I can inspect the code; (2) written by someone with expertise in the subject area; (3) well established for years and/or have a base of users. I do think certain sources are particularly reliable, e.g. [Ropenscience](https://ropensci.org/) which runs a software peer review process. 

To your comment about missing out on good things by only using CRAN:  CRAN has become especially difficult recently in package submission and very quick to archive packages that by and large are fine and perhaps failing one minor check on a very arcane system. Here's an [open letter](https://github.com/MilesMcBain/cran_change.org/blob/main/letter.md) regarding the topic and [one example](https://twitter.com/RaphaelS101/status/1506321629797883912) of a person who no longer will submit to CRAN given the difficulties. Additionally, there are repeated allegation of verbal abuse towards package submitters by a CRAN head honcho. I don't have permission to share names, but I think this means we are missing out on packages if we only rely on CRAN. My goal is to help my (research) community find the packages the need, regardless of the source. 

Would you like me to prepare a pull request for 'agromet'?

**Comment by jpiaskowski** [comment]
>  I was as much thinking about the piece of software that is left unmaintained on GitHub with no commits for X years with no CI and what heuristic you might have for something like that? 

Good point. I have not developed a system, but perhaps badges could come in handy? Is it passing 'R CMD Check'? What's the code coverage? Something that personally frustrates me is poor documentation - is there just the function reference manual and nothing more? 

I should be able to get to a PR next week.
