### ISSUE TITLE
Update Hydrology

### ISSUE THREAD

**Issue by boshek** [cran-task-views/Hydrology#117]
👋  @zeileis

What's the best to request an updating to the CRAN task view? We've had a few commits already to the task view but they don't seem to be updated on CRAN yet?

**Comment by zeileis** [comment]
It's online now. Part of the problem was that the task view couldn't be processed successfully due to a missing backtick. Please check by running `ctv2html()` or `check_ctv_packages()`. We are also working on an automatic creation of a GitHub issue in such cases but we haven't fully set this up, yet.

**Comment by boshek** [comment]
@zeileis let me know if you'd like any help with that. Also a GitHub action might be useful in this case.

**Comment by zeileis** [comment]
As you have seen, we have now the basic functionality for automatic creation of GH issues in place, we just need to adapt the scripts accordingly. We'll get there soon, I hope.

**Comment by boshek** [comment]
:wave: @zeileis 

Something isn't landing for me here. This task view hasn't been updated since we migrated over to GitHub. Is there a manual step that I need to do to update it before making commits to the markdown file in this repo? 

With respect to the functions in the {ctv} package, I am not seeing how they can be used with the markdown file.

If there is a better place to ask this, please let me know. Thanks!

**Comment by boshek** [comment]
Oops. Nevermind. Got it figured out now. I was no changing the date manually. Is the script that auto-uploads markdown files from GitHub to CRAN open? It might be nice to auto-update that date so that users don't have to. At least have some type of auto-incrementing system.

**Comment by zeileis** [comment]
The date/version of the task view should be reflected in both the repository on GitHub and on CRAN. It is typically the date where the last addition or removal of packages in the task view has been made. So I think it's not a good fit to set this only on the CRAN side upon update.
