### ISSUE TITLE
Package that provides recommendations to Task Views

### ISSUE THREAD

**Issue by DylanDijk** [cran-task-views/Hydrology#136]
I have created the [CTVsuggest](https://dylandijk.github.io/CTVsuggest/index.html) R package which aims to provide package suggestions to CRAN Task Views.  
I am writing this issue to advertise its use.

Once CTVsuggest is installed:
``` r
devtools::install_github("DylanDijk/CTVsuggest") 
```
The  `CTVsuggest()` function outputs package suggestions for a selected Task View, 
below I display the top 5 suggestions for the Hydrology Task View.

## Hydrology Task View Package Suggestions

``` r
library(CTVsuggest)
CTVsuggest(taskview = "Hydrology", n = 5)
```
``` r
#>               Hydrology      Packages
#> hubeau        0.9999599        hubeau
#> gumboot       0.9999589       gumboot
#> CSHShydRology 0.9997641 CSHShydRology
#> BLRPM         0.9989110         BLRPM
#> airGRdatasets 0.9982558 airGRdatasets
```

A description of how the package works, and in particular how the recommendation model is constructed, is provided in [this vignette](https://dylandijk.github.io/CTVsuggest/articles/CTVsuggest-Overview.html).

**Comment by boshek** [comment]
Hi there - thanks for this. For now it is working pretty well for community folks to submit the task view but I will keep this in mind. Thanks!
