### ISSUE TITLE
How to reference an R package on self-hosted GitLab server?

### ISSUE THREAD

**Issue by ThibHlln** [cran-task-views/Hydrology#142]
Hi,

There is an R package that we have developed that is on GitLab (not on CRAN, nor on GitHub): https://gitlab.irstea.fr/HYCAR-Hydro/evalhyd/evalhyd-r

So, I am wondering how we could include it in your list of hydrology-relevant packages, since the syntaxes `r pkg("package_name")` or `r github("username/repository_name")` in your markdown document will not work for us. 

What syntax should we use for GitLab repositories on self-hosted servers?

Thanks.

**Comment by boshek** [comment]
👋  thanks for reaching out. Is there any reason to not simply submit the package to CRAN? The task view is tied fairly tightly to CRAN so ideally all packages in the task view are also CRAN packages.
