### ISSUE TITLE
Add agriwater

### ISSUE THREAD

**Issue by cesarofs** [cran-task-views/Hydrology#147]
I think my package "agriwater" could be added to the task view. It was refactored recently. 

https://cran.r-project.org/package=agriwater

``r pkg("agriwater") provides spatial modeling of energy balance and actual evapotranspiration using satellite images and meteorological data. Options of satellite are: Landsat-8 (with and without thermal bands), Sentinel-2 and MODIS. Respectively spatial resolutions are 30, 100, 10 and 250 meters. User can use data from a single meteorological station or a grid of meteorological stations (using any spatial interpolation method) as described in *agriwater: An R package for spatial modelling of energy balance and actual evapotranspiration using satellite images and agrometeorological data* Silva, Teixeira, and Manzione ([2019](https://doi.org/10.1016/j.envsoft.2019.104497)).`

**Comment by boshek** [comment]
Great! Are you able to submit a PR for this?

**Comment by cesarofs** [comment]
Closed [#148 ](https://github.com/cran-task-views/Hydrology/pull/148) as completed. =D
