### ISSUE TITLE
Add Package PowerSDI 

### ISSUE THREAD

**Issue by gabrielblain** [cran-task-views/Hydrology#152]
I suggest package PowerSDI (https://cloud.r-project.org/web/packages/PowerSDI/index.html) be added to the Hydrology CTV.

The PowerSDI calculates two Standardised Drought Indices (SPI and SPEI) using NASA POWER Data. 
The package also verifies if the indices' estimates meet the assumption of normality and how well NASA POWER estimates represent real-world data. Indices are calculated in a routine mode. Potential evapotranspiration amounts and the difference between rainfall and potential evapotranspiration are also calculated. It adopts a basic time scale that splits each month into four periods where 'TS=4' corresponds to a 1-month length moving window (calculated 4 times per month) and 'TS=48' corresponds to a 12-month length moving window (calculated 4 times per month).
Gabriel Blain

**Comment by boshek** [comment]
Yeah that sounds great. Would you be willing to add them via a PR? Here is an example: https://github.com/cran-task-views/Hydrology/pull/148

**Comment by gabrielblain** [comment]
Thanks!
 I just need some time to do this. I'm not familiar with GitHub, so I have
to learn how to do this.
Please, let me know if there is another way.
Best

Em seg., 20 de nov. de 2023 às 15:27, Sam Albers ***@***.***>
escreveu:

**Comment by boshek** [comment]
No problem. I just did it myself :) 

Thanks for this!
