### ISSUE TITLE
Task view not being update

### ISSUE THREAD

**Issue by boshek** [cran-task-views/Hydrology#174]
@zeileis I am noticing that the task view is not being updated with new changes. Any ideas on that?

**Comment by zeileis** [comment]
Why do you think it isn't updated? The [version on CRAN](https://cran.r-project.org/view=Hydrology) looks up-to-date to me:

```
github <- readLines("https://raw.githubusercontent.com/cran-task-views/Hydrology/refs/heads/main/Hydrology.md")
cran <- readLines("https://cran.r-project.org/web/views/Hydrology.md")
all.equal(github, cran)
## [1] TRUE
identical(github, cran)
## [1] TRUE
```

A cronjob runs once per day and pulls the latest version of the .md from the main branch and updates the CRAN version correspondingly.

**Comment by zeileis** [comment]
That's the version number you assign in the .md: https://github.com/cran-task-views/Hydrology/blob/main/Hydrology.md?plain=1#L6

This is not changed automatically.

**Comment by boshek** [comment]
Ok thanks for that. I think I will try to automate that.
